server: 
  port: 8085
  
spring: 
  application:
    name: customer-service
  #Config-server details 
  profiles:    active:    - development
  cloud:    config:      uri:      - http://localhost:8888
    
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://mysqldb/Order_System      # for docker image
    url: jdbc:mysql://localhost:3306/Order_System  # for local
    username: root
    password: ENC(wpb2C3O3du5pp1h8S3ndFQ==)
    
  jpa:    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:      ddl-auto: update  zipkin:    enabled: true
    base-url: https://zipkin-service/
  sleuth:    sampler:      probability: 1
      
eureka:  client:    serviceUrl:
      defaultZone: http://127.0.0.1:9091/eureka/
      
jasypt:
  encryptor:
    password: appkey
    

      #zipkin server