version: '3.1'
services:
  myapp:
    image: employee-management
    restart: always
    container_name: employee-management
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./tmp/employeemngt
    ports:
    - 8082:8081
    links:
    - mongo
    depends_on:
    - mongo
    networks:
    - mongo_net
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: employee-management
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
    - 27017:27017
    volumes:
    - ./user.js:/docker-entrypoint-initdb.d/user.js:ro
    - ./mongo-volume:/mongodb/data
    networks:
    - mongo_net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myUserAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
    - mongo_net
    depends_on:
    - mongo
networks:
  mongo_net:
    driver: bridge